// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gotv_plus.proto

package GOTV_PLUS

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Match struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{0}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Match) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetMatchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesRequest) Reset()         { *m = GetMatchesRequest{} }
func (m *GetMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchesRequest) ProtoMessage()    {}
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{1}
}

func (m *GetMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesRequest.Unmarshal(m, b)
}
func (m *GetMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesRequest.Merge(m, src)
}
func (m *GetMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchesRequest.Size(m)
}
func (m *GetMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesRequest proto.InternalMessageInfo

type GetMatchesReply struct {
	Match                []*Match `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,3,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesReply) Reset()         { *m = GetMatchesReply{} }
func (m *GetMatchesReply) String() string { return proto.CompactTextString(m) }
func (*GetMatchesReply) ProtoMessage()    {}
func (*GetMatchesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{2}
}

func (m *GetMatchesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesReply.Unmarshal(m, b)
}
func (m *GetMatchesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesReply.Marshal(b, m, deterministic)
}
func (m *GetMatchesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesReply.Merge(m, src)
}
func (m *GetMatchesReply) XXX_Size() int {
	return xxx_messageInfo_GetMatchesReply.Size(m)
}
func (m *GetMatchesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesReply proto.InternalMessageInfo

func (m *GetMatchesReply) GetMatch() []*Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *GetMatchesReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *GetMatchesReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type MarkIDRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDRequest) Reset()         { *m = MarkIDRequest{} }
func (m *MarkIDRequest) String() string { return proto.CompactTextString(m) }
func (*MarkIDRequest) ProtoMessage()    {}
func (*MarkIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{3}
}

func (m *MarkIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDRequest.Unmarshal(m, b)
}
func (m *MarkIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDRequest.Marshal(b, m, deterministic)
}
func (m *MarkIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDRequest.Merge(m, src)
}
func (m *MarkIDRequest) XXX_Size() int {
	return xxx_messageInfo_MarkIDRequest.Size(m)
}
func (m *MarkIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDRequest proto.InternalMessageInfo

func (m *MarkIDRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MarkIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MarkIDReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDReply) Reset()         { *m = MarkIDReply{} }
func (m *MarkIDReply) String() string { return proto.CompactTextString(m) }
func (*MarkIDReply) ProtoMessage()    {}
func (*MarkIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{4}
}

func (m *MarkIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDReply.Unmarshal(m, b)
}
func (m *MarkIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDReply.Marshal(b, m, deterministic)
}
func (m *MarkIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDReply.Merge(m, src)
}
func (m *MarkIDReply) XXX_Size() int {
	return xxx_messageInfo_MarkIDReply.Size(m)
}
func (m *MarkIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDReply proto.InternalMessageInfo

func (m *MarkIDReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *MarkIDReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Match)(nil), "GOTV_PLUS.Match")
	proto.RegisterType((*GetMatchesRequest)(nil), "GOTV_PLUS.GetMatchesRequest")
	proto.RegisterType((*GetMatchesReply)(nil), "GOTV_PLUS.GetMatchesReply")
	proto.RegisterType((*MarkIDRequest)(nil), "GOTV_PLUS.MarkIDRequest")
	proto.RegisterType((*MarkIDReply)(nil), "GOTV_PLUS.MarkIDReply")
}

func init() { proto.RegisterFile("gotv_plus.proto", fileDescriptor_d8a69789a3c4d4fd) }

var fileDescriptor_d8a69789a3c4d4fd = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcf, 0x2f, 0x29,
	0x8b, 0x2f, 0xc8, 0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x74, 0xf7, 0x0f,
	0x09, 0x8b, 0x0f, 0xf0, 0x09, 0x0d, 0x56, 0xd2, 0xe5, 0x62, 0xf5, 0x4d, 0x2c, 0x49, 0xce, 0x10,
	0x12, 0xe1, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0x70, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0xc0, 0x42, 0x4c, 0x99, 0x29, 0x4a, 0xc2,
	0x5c, 0x82, 0xee, 0xa9, 0x25, 0x60, 0x1d, 0xa9, 0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x4a, 0xc5, 0x5c, 0xfc, 0xc8, 0x82, 0x05, 0x39, 0x95, 0x42, 0x6a, 0x5c, 0xac, 0xb9, 0x20, 0xbe,
	0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x80, 0x1e, 0xdc, 0x46, 0x3d, 0xb0, 0xba, 0x20, 0x88,
	0x34, 0xc8, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0xb0, 0x15, 0x1c, 0x41, 0x10, 0x8e, 0x90, 0x12,
	0x17, 0x0f, 0x98, 0x91, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xc1, 0x0c, 0xb6, 0x1f, 0x45,
	0x4c, 0xc9, 0x94, 0x8b, 0xd7, 0x37, 0xb1, 0x28, 0xdb, 0xd3, 0x05, 0xea, 0x0a, 0x22, 0x3d, 0xe0,
	0xce, 0xc5, 0x0d, 0xd3, 0x06, 0x72, 0x27, 0xdc, 0x7e, 0x46, 0x7c, 0xf6, 0x33, 0x61, 0xda, 0x6f,
	0x34, 0x99, 0x91, 0x0b, 0x1a, 0x8c, 0x39, 0xa5, 0xc5, 0x42, 0x1e, 0x5c, 0x5c, 0x88, 0x20, 0x10,
	0x92, 0x41, 0xf2, 0x2e, 0x46, 0x70, 0x49, 0x49, 0xe1, 0x90, 0x2d, 0xc8, 0xa9, 0x54, 0x62, 0x10,
	0xb2, 0xe1, 0x62, 0x83, 0x38, 0x50, 0x48, 0x02, 0x25, 0xd0, 0x90, 0xbc, 0x2a, 0x25, 0x86, 0x45,
	0x06, 0xac, 0x3b, 0x89, 0x0d, 0x1c, 0xc1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xc6,
	0x11, 0x59, 0xf3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GOTV_PlusClient is the client API for GOTV_Plus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GOTV_PlusClient interface {
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error)
	MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error)
}

type gOTV_PlusClient struct {
	cc *grpc.ClientConn
}

func NewGOTV_PlusClient(cc *grpc.ClientConn) GOTV_PlusClient {
	return &gOTV_PlusClient{cc}
}

func (c *gOTV_PlusClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error) {
	out := new(GetMatchesReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error) {
	out := new(MarkIDReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/MarkID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GOTV_PlusServer is the server API for GOTV_Plus service.
type GOTV_PlusServer interface {
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
	MarkID(context.Context, *MarkIDRequest) (*MarkIDReply, error)
}

// UnimplementedGOTV_PlusServer can be embedded to have forward compatible implementations.
type UnimplementedGOTV_PlusServer struct {
}

func (*UnimplementedGOTV_PlusServer) GetMatches(ctx context.Context, req *GetMatchesRequest) (*GetMatchesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (*UnimplementedGOTV_PlusServer) MarkID(ctx context.Context, req *MarkIDRequest) (*MarkIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkID not implemented")
}

func RegisterGOTV_PlusServer(s *grpc.Server, srv GOTV_PlusServer) {
	s.RegisterService(&_GOTV_Plus_serviceDesc, srv)
}

func _GOTV_Plus_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_MarkID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).MarkID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/MarkID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).MarkID(ctx, req.(*MarkIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GOTV_Plus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GOTV_PLUS.GOTV_Plus",
	HandlerType: (*GOTV_PlusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatches",
			Handler:    _GOTV_Plus_GetMatches_Handler,
		},
		{
			MethodName: "MarkID",
			Handler:    _GOTV_Plus_MarkID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotv_plus.proto",
}
