// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gotv_plus.proto

package GOTV_PLUS

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MatchBinary struct {
	Token                string              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SignupFragment       uint32              `protobuf:"varint,3,opt,name=signup_fragment,json=signupFragment,proto3" json:"signup_fragment,omitempty"`
	StartFrame           []*StartFrameBinary `protobuf:"bytes,4,rep,name=StartFrame,proto3" json:"StartFrame,omitempty"`
	FullFrame            []*FullFrameBinary  `protobuf:"bytes,5,rep,name=FullFrame,proto3" json:"FullFrame,omitempty"`
	DeltaFrame           []*DeltaFrameBinary `protobuf:"bytes,6,rep,name=DeltaFrame,proto3" json:"DeltaFrame,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MatchBinary) Reset()         { *m = MatchBinary{} }
func (m *MatchBinary) String() string { return proto.CompactTextString(m) }
func (*MatchBinary) ProtoMessage()    {}
func (*MatchBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{0}
}

func (m *MatchBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchBinary.Unmarshal(m, b)
}
func (m *MatchBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchBinary.Marshal(b, m, deterministic)
}
func (m *MatchBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchBinary.Merge(m, src)
}
func (m *MatchBinary) XXX_Size() int {
	return xxx_messageInfo_MatchBinary.Size(m)
}
func (m *MatchBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchBinary.DiscardUnknown(m)
}

var xxx_messageInfo_MatchBinary proto.InternalMessageInfo

func (m *MatchBinary) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MatchBinary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MatchBinary) GetSignupFragment() uint32 {
	if m != nil {
		return m.SignupFragment
	}
	return 0
}

func (m *MatchBinary) GetStartFrame() []*StartFrameBinary {
	if m != nil {
		return m.StartFrame
	}
	return nil
}

func (m *MatchBinary) GetFullFrame() []*FullFrameBinary {
	if m != nil {
		return m.FullFrame
	}
	return nil
}

func (m *MatchBinary) GetDeltaFrame() []*DeltaFrameBinary {
	if m != nil {
		return m.DeltaFrame
	}
	return nil
}

type StartFrameBinary struct {
	Fragment             uint32               `protobuf:"varint,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Tps                  uint32               `protobuf:"varint,2,opt,name=tps,proto3" json:"tps,omitempty"`
	Map                  string               `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	Protocol             uint32               `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Body                 []byte               `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	At                   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StartFrameBinary) Reset()         { *m = StartFrameBinary{} }
func (m *StartFrameBinary) String() string { return proto.CompactTextString(m) }
func (*StartFrameBinary) ProtoMessage()    {}
func (*StartFrameBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{1}
}

func (m *StartFrameBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartFrameBinary.Unmarshal(m, b)
}
func (m *StartFrameBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartFrameBinary.Marshal(b, m, deterministic)
}
func (m *StartFrameBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartFrameBinary.Merge(m, src)
}
func (m *StartFrameBinary) XXX_Size() int {
	return xxx_messageInfo_StartFrameBinary.Size(m)
}
func (m *StartFrameBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_StartFrameBinary.DiscardUnknown(m)
}

var xxx_messageInfo_StartFrameBinary proto.InternalMessageInfo

func (m *StartFrameBinary) GetFragment() uint32 {
	if m != nil {
		return m.Fragment
	}
	return 0
}

func (m *StartFrameBinary) GetTps() uint32 {
	if m != nil {
		return m.Tps
	}
	return 0
}

func (m *StartFrameBinary) GetMap() string {
	if m != nil {
		return m.Map
	}
	return ""
}

func (m *StartFrameBinary) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *StartFrameBinary) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *StartFrameBinary) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

type FullFrameBinary struct {
	Fragment             uint32               `protobuf:"varint,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Tick                 uint64               `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Body                 []byte               `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	At                   *timestamp.Timestamp `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FullFrameBinary) Reset()         { *m = FullFrameBinary{} }
func (m *FullFrameBinary) String() string { return proto.CompactTextString(m) }
func (*FullFrameBinary) ProtoMessage()    {}
func (*FullFrameBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{2}
}

func (m *FullFrameBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullFrameBinary.Unmarshal(m, b)
}
func (m *FullFrameBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullFrameBinary.Marshal(b, m, deterministic)
}
func (m *FullFrameBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullFrameBinary.Merge(m, src)
}
func (m *FullFrameBinary) XXX_Size() int {
	return xxx_messageInfo_FullFrameBinary.Size(m)
}
func (m *FullFrameBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_FullFrameBinary.DiscardUnknown(m)
}

var xxx_messageInfo_FullFrameBinary proto.InternalMessageInfo

func (m *FullFrameBinary) GetFragment() uint32 {
	if m != nil {
		return m.Fragment
	}
	return 0
}

func (m *FullFrameBinary) GetTick() uint64 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *FullFrameBinary) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *FullFrameBinary) GetAt() *timestamp.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

type DeltaFrameBinary struct {
	Fragment             uint32   `protobuf:"varint,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Endtick              uint64   `protobuf:"varint,2,opt,name=endtick,proto3" json:"endtick,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeltaFrameBinary) Reset()         { *m = DeltaFrameBinary{} }
func (m *DeltaFrameBinary) String() string { return proto.CompactTextString(m) }
func (*DeltaFrameBinary) ProtoMessage()    {}
func (*DeltaFrameBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{3}
}

func (m *DeltaFrameBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeltaFrameBinary.Unmarshal(m, b)
}
func (m *DeltaFrameBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeltaFrameBinary.Marshal(b, m, deterministic)
}
func (m *DeltaFrameBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeltaFrameBinary.Merge(m, src)
}
func (m *DeltaFrameBinary) XXX_Size() int {
	return xxx_messageInfo_DeltaFrameBinary.Size(m)
}
func (m *DeltaFrameBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_DeltaFrameBinary.DiscardUnknown(m)
}

var xxx_messageInfo_DeltaFrameBinary proto.InternalMessageInfo

func (m *DeltaFrameBinary) GetFragment() uint32 {
	if m != nil {
		return m.Fragment
	}
	return 0
}

func (m *DeltaFrameBinary) GetEndtick() uint64 {
	if m != nil {
		return m.Endtick
	}
	return 0
}

func (m *DeltaFrameBinary) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Match struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{4}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Match) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetMatchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesRequest) Reset()         { *m = GetMatchesRequest{} }
func (m *GetMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchesRequest) ProtoMessage()    {}
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{5}
}

func (m *GetMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesRequest.Unmarshal(m, b)
}
func (m *GetMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesRequest.Merge(m, src)
}
func (m *GetMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchesRequest.Size(m)
}
func (m *GetMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesRequest proto.InternalMessageInfo

type GetMatchesReply struct {
	Match                []*Match `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,3,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesReply) Reset()         { *m = GetMatchesReply{} }
func (m *GetMatchesReply) String() string { return proto.CompactTextString(m) }
func (*GetMatchesReply) ProtoMessage()    {}
func (*GetMatchesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{6}
}

func (m *GetMatchesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesReply.Unmarshal(m, b)
}
func (m *GetMatchesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesReply.Marshal(b, m, deterministic)
}
func (m *GetMatchesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesReply.Merge(m, src)
}
func (m *GetMatchesReply) XXX_Size() int {
	return xxx_messageInfo_GetMatchesReply.Size(m)
}
func (m *GetMatchesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesReply proto.InternalMessageInfo

func (m *GetMatchesReply) GetMatch() []*Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *GetMatchesReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *GetMatchesReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type GetMatchRequest struct {
	// Types that are valid to be assigned to Ids:
	//	*GetMatchRequest_Token
	//	*GetMatchRequest_Id
	Ids                  isGetMatchRequest_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMatchRequest) Reset()         { *m = GetMatchRequest{} }
func (m *GetMatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchRequest) ProtoMessage()    {}
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{7}
}

func (m *GetMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchRequest.Unmarshal(m, b)
}
func (m *GetMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchRequest.Merge(m, src)
}
func (m *GetMatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchRequest.Size(m)
}
func (m *GetMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchRequest proto.InternalMessageInfo

type isGetMatchRequest_Ids interface {
	isGetMatchRequest_Ids()
}

type GetMatchRequest_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type GetMatchRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*GetMatchRequest_Token) isGetMatchRequest_Ids() {}

func (*GetMatchRequest_Id) isGetMatchRequest_Ids() {}

func (m *GetMatchRequest) GetIds() isGetMatchRequest_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetMatchRequest) GetToken() string {
	if x, ok := m.GetIds().(*GetMatchRequest_Token); ok {
		return x.Token
	}
	return ""
}

func (m *GetMatchRequest) GetId() string {
	if x, ok := m.GetIds().(*GetMatchRequest_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetMatchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetMatchRequest_Token)(nil),
		(*GetMatchRequest_Id)(nil),
	}
}

type DeleteMatchRequest struct {
	// Types that are valid to be assigned to Ids:
	//	*DeleteMatchRequest_Token
	//	*DeleteMatchRequest_Id
	Ids                  isDeleteMatchRequest_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeleteMatchRequest) Reset()         { *m = DeleteMatchRequest{} }
func (m *DeleteMatchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMatchRequest) ProtoMessage()    {}
func (*DeleteMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{8}
}

func (m *DeleteMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMatchRequest.Unmarshal(m, b)
}
func (m *DeleteMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMatchRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMatchRequest.Merge(m, src)
}
func (m *DeleteMatchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMatchRequest.Size(m)
}
func (m *DeleteMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMatchRequest proto.InternalMessageInfo

type isDeleteMatchRequest_Ids interface {
	isDeleteMatchRequest_Ids()
}

type DeleteMatchRequest_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type DeleteMatchRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*DeleteMatchRequest_Token) isDeleteMatchRequest_Ids() {}

func (*DeleteMatchRequest_Id) isDeleteMatchRequest_Ids() {}

func (m *DeleteMatchRequest) GetIds() isDeleteMatchRequest_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeleteMatchRequest) GetToken() string {
	if x, ok := m.GetIds().(*DeleteMatchRequest_Token); ok {
		return x.Token
	}
	return ""
}

func (m *DeleteMatchRequest) GetId() string {
	if x, ok := m.GetIds().(*DeleteMatchRequest_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteMatchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteMatchRequest_Token)(nil),
		(*DeleteMatchRequest_Id)(nil),
	}
}

type DeleteMatchReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMatchReply) Reset()         { *m = DeleteMatchReply{} }
func (m *DeleteMatchReply) String() string { return proto.CompactTextString(m) }
func (*DeleteMatchReply) ProtoMessage()    {}
func (*DeleteMatchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{9}
}

func (m *DeleteMatchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMatchReply.Unmarshal(m, b)
}
func (m *DeleteMatchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMatchReply.Marshal(b, m, deterministic)
}
func (m *DeleteMatchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMatchReply.Merge(m, src)
}
func (m *DeleteMatchReply) XXX_Size() int {
	return xxx_messageInfo_DeleteMatchReply.Size(m)
}
func (m *DeleteMatchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMatchReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMatchReply proto.InternalMessageInfo

func (m *DeleteMatchReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *DeleteMatchReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type MarkIDRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDRequest) Reset()         { *m = MarkIDRequest{} }
func (m *MarkIDRequest) String() string { return proto.CompactTextString(m) }
func (*MarkIDRequest) ProtoMessage()    {}
func (*MarkIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{10}
}

func (m *MarkIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDRequest.Unmarshal(m, b)
}
func (m *MarkIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDRequest.Marshal(b, m, deterministic)
}
func (m *MarkIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDRequest.Merge(m, src)
}
func (m *MarkIDRequest) XXX_Size() int {
	return xxx_messageInfo_MarkIDRequest.Size(m)
}
func (m *MarkIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDRequest proto.InternalMessageInfo

func (m *MarkIDRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MarkIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MarkIDReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDReply) Reset()         { *m = MarkIDReply{} }
func (m *MarkIDReply) String() string { return proto.CompactTextString(m) }
func (*MarkIDReply) ProtoMessage()    {}
func (*MarkIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{11}
}

func (m *MarkIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDReply.Unmarshal(m, b)
}
func (m *MarkIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDReply.Marshal(b, m, deterministic)
}
func (m *MarkIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDReply.Merge(m, src)
}
func (m *MarkIDReply) XXX_Size() int {
	return xxx_messageInfo_MarkIDReply.Size(m)
}
func (m *MarkIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDReply proto.InternalMessageInfo

func (m *MarkIDReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *MarkIDReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type SaveMatchToFileRequest struct {
	// Types that are valid to be assigned to Ids:
	//	*SaveMatchToFileRequest_Token
	//	*SaveMatchToFileRequest_Id
	Ids                  isSaveMatchToFileRequest_Ids `protobuf_oneof:"ids"`
	Path                 string                       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SaveMatchToFileRequest) Reset()         { *m = SaveMatchToFileRequest{} }
func (m *SaveMatchToFileRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMatchToFileRequest) ProtoMessage()    {}
func (*SaveMatchToFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{12}
}

func (m *SaveMatchToFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMatchToFileRequest.Unmarshal(m, b)
}
func (m *SaveMatchToFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMatchToFileRequest.Marshal(b, m, deterministic)
}
func (m *SaveMatchToFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMatchToFileRequest.Merge(m, src)
}
func (m *SaveMatchToFileRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMatchToFileRequest.Size(m)
}
func (m *SaveMatchToFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMatchToFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMatchToFileRequest proto.InternalMessageInfo

type isSaveMatchToFileRequest_Ids interface {
	isSaveMatchToFileRequest_Ids()
}

type SaveMatchToFileRequest_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type SaveMatchToFileRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*SaveMatchToFileRequest_Token) isSaveMatchToFileRequest_Ids() {}

func (*SaveMatchToFileRequest_Id) isSaveMatchToFileRequest_Ids() {}

func (m *SaveMatchToFileRequest) GetIds() isSaveMatchToFileRequest_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SaveMatchToFileRequest) GetToken() string {
	if x, ok := m.GetIds().(*SaveMatchToFileRequest_Token); ok {
		return x.Token
	}
	return ""
}

func (m *SaveMatchToFileRequest) GetId() string {
	if x, ok := m.GetIds().(*SaveMatchToFileRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (m *SaveMatchToFileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SaveMatchToFileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SaveMatchToFileRequest_Token)(nil),
		(*SaveMatchToFileRequest_Id)(nil),
	}
}

type SaveMatchToFileReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMatchToFileReply) Reset()         { *m = SaveMatchToFileReply{} }
func (m *SaveMatchToFileReply) String() string { return proto.CompactTextString(m) }
func (*SaveMatchToFileReply) ProtoMessage()    {}
func (*SaveMatchToFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{13}
}

func (m *SaveMatchToFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMatchToFileReply.Unmarshal(m, b)
}
func (m *SaveMatchToFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMatchToFileReply.Marshal(b, m, deterministic)
}
func (m *SaveMatchToFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMatchToFileReply.Merge(m, src)
}
func (m *SaveMatchToFileReply) XXX_Size() int {
	return xxx_messageInfo_SaveMatchToFileReply.Size(m)
}
func (m *SaveMatchToFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMatchToFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMatchToFileReply proto.InternalMessageInfo

func (m *SaveMatchToFileReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *SaveMatchToFileReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type LoadMatchFromFileRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMatchFromFileRequest) Reset()         { *m = LoadMatchFromFileRequest{} }
func (m *LoadMatchFromFileRequest) String() string { return proto.CompactTextString(m) }
func (*LoadMatchFromFileRequest) ProtoMessage()    {}
func (*LoadMatchFromFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{14}
}

func (m *LoadMatchFromFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatchFromFileRequest.Unmarshal(m, b)
}
func (m *LoadMatchFromFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatchFromFileRequest.Marshal(b, m, deterministic)
}
func (m *LoadMatchFromFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatchFromFileRequest.Merge(m, src)
}
func (m *LoadMatchFromFileRequest) XXX_Size() int {
	return xxx_messageInfo_LoadMatchFromFileRequest.Size(m)
}
func (m *LoadMatchFromFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatchFromFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatchFromFileRequest proto.InternalMessageInfo

func (m *LoadMatchFromFileRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoadMatchFromFileReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,3,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMatchFromFileReply) Reset()         { *m = LoadMatchFromFileReply{} }
func (m *LoadMatchFromFileReply) String() string { return proto.CompactTextString(m) }
func (*LoadMatchFromFileReply) ProtoMessage()    {}
func (*LoadMatchFromFileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f259ec5e0ea3f7d2, []int{15}
}

func (m *LoadMatchFromFileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMatchFromFileReply.Unmarshal(m, b)
}
func (m *LoadMatchFromFileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMatchFromFileReply.Marshal(b, m, deterministic)
}
func (m *LoadMatchFromFileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMatchFromFileReply.Merge(m, src)
}
func (m *LoadMatchFromFileReply) XXX_Size() int {
	return xxx_messageInfo_LoadMatchFromFileReply.Size(m)
}
func (m *LoadMatchFromFileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMatchFromFileReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMatchFromFileReply proto.InternalMessageInfo

func (m *LoadMatchFromFileReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoadMatchFromFileReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *LoadMatchFromFileReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

func init() {
	proto.RegisterType((*MatchBinary)(nil), "GOTV_PLUS.MatchBinary")
	proto.RegisterType((*StartFrameBinary)(nil), "GOTV_PLUS.StartFrameBinary")
	proto.RegisterType((*FullFrameBinary)(nil), "GOTV_PLUS.FullFrameBinary")
	proto.RegisterType((*DeltaFrameBinary)(nil), "GOTV_PLUS.DeltaFrameBinary")
	proto.RegisterType((*Match)(nil), "GOTV_PLUS.Match")
	proto.RegisterType((*GetMatchesRequest)(nil), "GOTV_PLUS.GetMatchesRequest")
	proto.RegisterType((*GetMatchesReply)(nil), "GOTV_PLUS.GetMatchesReply")
	proto.RegisterType((*GetMatchRequest)(nil), "GOTV_PLUS.GetMatchRequest")
	proto.RegisterType((*DeleteMatchRequest)(nil), "GOTV_PLUS.DeleteMatchRequest")
	proto.RegisterType((*DeleteMatchReply)(nil), "GOTV_PLUS.DeleteMatchReply")
	proto.RegisterType((*MarkIDRequest)(nil), "GOTV_PLUS.MarkIDRequest")
	proto.RegisterType((*MarkIDReply)(nil), "GOTV_PLUS.MarkIDReply")
	proto.RegisterType((*SaveMatchToFileRequest)(nil), "GOTV_PLUS.SaveMatchToFileRequest")
	proto.RegisterType((*SaveMatchToFileReply)(nil), "GOTV_PLUS.SaveMatchToFileReply")
	proto.RegisterType((*LoadMatchFromFileRequest)(nil), "GOTV_PLUS.LoadMatchFromFileRequest")
	proto.RegisterType((*LoadMatchFromFileReply)(nil), "GOTV_PLUS.LoadMatchFromFileReply")
}

func init() { proto.RegisterFile("proto/gotv_plus.proto", fileDescriptor_f259ec5e0ea3f7d2) }

var fileDescriptor_f259ec5e0ea3f7d2 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x9d, 0xc3, 0xdf, 0x4c, 0x0f, 0x49, 0xe7, 0x2f, 0x91, 0xe5, 0x82, 0x9a, 0x2e, 0x12,
	0x44, 0x48, 0xa4, 0xa8, 0x08, 0x09, 0x01, 0x57, 0x55, 0x49, 0x8b, 0x68, 0x45, 0xe5, 0x16, 0xb8,
	0xa1, 0xaa, 0xb6, 0xcd, 0x36, 0xb5, 0x6a, 0x67, 0x8d, 0xbd, 0xae, 0x94, 0x4b, 0xde, 0x80, 0x27,
	0xe1, 0x69, 0x78, 0x20, 0xe4, 0x5d, 0x9f, 0x12, 0xbb, 0x51, 0xa1, 0x77, 0x73, 0x9e, 0x6f, 0x66,
	0xbe, 0xb5, 0xe1, 0x81, 0xe7, 0x73, 0xc1, 0xb7, 0x46, 0x5c, 0xdc, 0x9c, 0x79, 0x4e, 0x18, 0xf4,
	0xa5, 0x8e, 0xcd, 0xbd, 0x4f, 0x27, 0x5f, 0xce, 0x8e, 0x0e, 0x3e, 0x1f, 0x9b, 0x1b, 0x23, 0xce,
	0x47, 0x0e, 0xdb, 0x92, 0x8e, 0xf3, 0xf0, 0x72, 0x4b, 0xd8, 0x2e, 0x0b, 0x04, 0x75, 0x3d, 0x15,
	0x4b, 0x7e, 0xea, 0xb0, 0x78, 0x48, 0xc5, 0xc5, 0xd5, 0x8e, 0x3d, 0xa6, 0xfe, 0x04, 0xd7, 0xa0,
	0x2e, 0xf8, 0x35, 0x1b, 0x1b, 0x5a, 0x57, 0xeb, 0x35, 0x2d, 0xa5, 0xe0, 0x0a, 0xe8, 0xf6, 0xd0,
	0xd0, 0xa5, 0x49, 0xb7, 0x87, 0xf8, 0x14, 0x5a, 0x81, 0x3d, 0x1a, 0x87, 0xde, 0xd9, 0xa5, 0x4f,
	0x47, 0x2e, 0x1b, 0x0b, 0xa3, 0xda, 0xd5, 0x7a, 0xcb, 0xd6, 0x8a, 0x32, 0x0f, 0x62, 0x2b, 0xbe,
	0x05, 0x38, 0x16, 0xd4, 0x17, 0x03, 0x9f, 0xba, 0xcc, 0xa8, 0x75, 0xab, 0xbd, 0xc5, 0xed, 0xf5,
	0x7e, 0x8a, 0xaf, 0x9f, 0x39, 0x55, 0x7f, 0x2b, 0x17, 0x8e, 0xaf, 0xa1, 0x39, 0x08, 0x1d, 0x47,
	0xe5, 0xd6, 0x65, 0xae, 0x99, 0xcb, 0x4d, 0x7d, 0x71, 0x6a, 0x16, 0x1c, 0xb5, 0xdd, 0x65, 0x8e,
	0xa0, 0x2a, 0xb5, 0x51, 0x68, 0x9b, 0x39, 0x93, 0xb6, 0x99, 0x85, 0xfc, 0xd2, 0xa0, 0x3d, 0x8b,
	0x0b, 0x4d, 0x58, 0x48, 0x47, 0xd5, 0xe4, 0xa8, 0xa9, 0x8e, 0x6d, 0xa8, 0x0a, 0x2f, 0x90, 0xeb,
	0x59, 0xb6, 0x22, 0x31, 0xb2, 0xb8, 0xd4, 0x93, 0x3b, 0x69, 0x5a, 0x91, 0x18, 0xe5, 0xcb, 0x85,
	0x5f, 0x70, 0xc7, 0xa8, 0xa9, 0xfc, 0x44, 0x47, 0x84, 0xda, 0x39, 0x1f, 0x4e, 0x8c, 0x7a, 0x57,
	0xeb, 0x2d, 0x59, 0x52, 0xc6, 0x67, 0xa0, 0x53, 0x61, 0x34, 0xba, 0x9a, 0x1c, 0x5a, 0x5d, 0xb1,
	0x9f, 0x5c, 0xb1, 0x7f, 0x92, 0x5c, 0xd1, 0xd2, 0xa9, 0x20, 0x3f, 0x34, 0x68, 0xcd, 0x2c, 0x63,
	0x2e, 0x5e, 0x84, 0x9a, 0xb0, 0x2f, 0xae, 0x25, 0xe0, 0x9a, 0x25, 0xe5, 0x14, 0x43, 0xb5, 0x80,
	0xa1, 0x76, 0x27, 0x0c, 0xdf, 0xa0, 0x3d, 0xbb, 0xd4, 0xb9, 0x18, 0x0c, 0xf8, 0x8f, 0x8d, 0x87,
	0x39, 0x18, 0x89, 0x5a, 0x86, 0x84, 0x3c, 0x87, 0xba, 0x24, 0xe9, 0xdd, 0xe8, 0x49, 0xfe, 0x87,
	0xd5, 0x3d, 0x26, 0x64, 0x06, 0x0b, 0x2c, 0xf6, 0x3d, 0x64, 0x81, 0x20, 0x01, 0xb4, 0xf2, 0x46,
	0xcf, 0x99, 0xe0, 0x13, 0xa8, 0xbb, 0x91, 0x6e, 0x68, 0x92, 0x21, 0xed, 0x1c, 0x43, 0x64, 0x9c,
	0xa5, 0xdc, 0x51, 0x57, 0xe6, 0xfb, 0xdc, 0x97, 0x2d, 0x16, 0x2c, 0xa5, 0x20, 0x81, 0x25, 0x29,
	0xb8, 0x2c, 0x08, 0xe8, 0x88, 0xc5, 0xd7, 0x9e, 0xb2, 0x91, 0x9d, 0xac, 0x69, 0x8c, 0x03, 0x3b,
	0x53, 0x23, 0xec, 0x57, 0x92, 0x21, 0xda, 0xd9, 0x10, 0xfb, 0x95, 0x68, 0x8c, 0x9d, 0x3a, 0x54,
	0xed, 0x61, 0x40, 0xde, 0x03, 0xee, 0x32, 0x87, 0x09, 0x76, 0xbf, 0x32, 0x07, 0xf2, 0x42, 0x59,
	0x99, 0x68, 0x01, 0xe9, 0x60, 0xda, 0xbc, 0xc1, 0xf4, 0x92, 0xc1, 0x5e, 0xc1, 0xf2, 0x21, 0xf5,
	0xaf, 0x3f, 0xec, 0x26, 0x78, 0xee, 0x76, 0x99, 0xbd, 0xe8, 0x6b, 0xa3, 0xd2, 0xee, 0xd7, 0xff,
	0x14, 0x3a, 0xc7, 0xf4, 0x46, 0xcd, 0x72, 0xc2, 0x07, 0xb6, 0xc3, 0xfe, 0x7a, 0x31, 0x11, 0xd3,
	0x3c, 0x2a, 0xae, 0xe2, 0xc3, 0x49, 0x39, 0x59, 0xd6, 0x11, 0xac, 0x15, 0xca, 0xdf, 0x0f, 0xf0,
	0x0b, 0x30, 0x0e, 0x38, 0x1d, 0xca, 0x8a, 0x03, 0x9f, 0xbb, 0x79, 0xc8, 0xa5, 0xbb, 0x23, 0x57,
	0xd0, 0x29, 0xc9, 0x88, 0x51, 0x94, 0xec, 0xfa, 0x9f, 0x59, 0xba, 0xfd, 0xbb, 0x0a, 0xf1, 0x3f,
	0xc3, 0x09, 0x03, 0xdc, 0x07, 0xc8, 0x1e, 0x0a, 0x3e, 0xcc, 0x3d, 0x8a, 0xc2, 0xa3, 0x32, 0xcd,
	0x5b, 0xbc, 0x9e, 0x33, 0x21, 0x15, 0x7c, 0x03, 0x0b, 0x89, 0x11, 0xcb, 0x22, 0x93, 0x2a, 0x85,
	0x87, 0x47, 0x2a, 0xf8, 0x11, 0x16, 0x73, 0x74, 0xc5, 0x47, 0xd3, 0x5f, 0xef, 0x99, 0xd7, 0x60,
	0xae, 0xdf, 0xe6, 0x56, 0x40, 0xde, 0x41, 0x43, 0xd1, 0x0e, 0x8d, 0xa9, 0x56, 0x39, 0x02, 0x9b,
	0x9d, 0x12, 0x8f, 0xca, 0xfe, 0x0a, 0xad, 0x19, 0x32, 0xe0, 0x66, 0xfe, 0x1f, 0x56, 0xca, 0x43,
	0x73, 0x63, 0x5e, 0x88, 0x2a, 0x7c, 0x0a, 0xab, 0x85, 0x0b, 0xe3, 0xe3, 0x5c, 0xde, 0x6d, 0x8c,
	0x31, 0x37, 0xe7, 0x07, 0xc9, 0xf2, 0xe7, 0x0d, 0xf9, 0xad, 0x7e, 0xf9, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x04, 0xe2, 0xe3, 0x24, 0x27, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GOTV_PlusClient is the client API for GOTV_Plus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GOTV_PlusClient interface {
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error)
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*Match, error)
	DeleteMatch(ctx context.Context, in *DeleteMatchRequest, opts ...grpc.CallOption) (*DeleteMatchReply, error)
	MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error)
	SaveMatchToFile(ctx context.Context, in *SaveMatchToFileRequest, opts ...grpc.CallOption) (*SaveMatchToFileReply, error)
	LoadMatchFromFile(ctx context.Context, in *LoadMatchFromFileRequest, opts ...grpc.CallOption) (*LoadMatchFromFileReply, error)
}

type gOTV_PlusClient struct {
	cc *grpc.ClientConn
}

func NewGOTV_PlusClient(cc *grpc.ClientConn) GOTV_PlusClient {
	return &gOTV_PlusClient{cc}
}

func (c *gOTV_PlusClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error) {
	out := new(GetMatchesReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*Match, error) {
	out := new(Match)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/GetMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) DeleteMatch(ctx context.Context, in *DeleteMatchRequest, opts ...grpc.CallOption) (*DeleteMatchReply, error) {
	out := new(DeleteMatchReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/DeleteMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error) {
	out := new(MarkIDReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/MarkID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) SaveMatchToFile(ctx context.Context, in *SaveMatchToFileRequest, opts ...grpc.CallOption) (*SaveMatchToFileReply, error) {
	out := new(SaveMatchToFileReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/SaveMatchToFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) LoadMatchFromFile(ctx context.Context, in *LoadMatchFromFileRequest, opts ...grpc.CallOption) (*LoadMatchFromFileReply, error) {
	out := new(LoadMatchFromFileReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/LoadMatchFromFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GOTV_PlusServer is the server API for GOTV_Plus service.
type GOTV_PlusServer interface {
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
	GetMatch(context.Context, *GetMatchRequest) (*Match, error)
	DeleteMatch(context.Context, *DeleteMatchRequest) (*DeleteMatchReply, error)
	MarkID(context.Context, *MarkIDRequest) (*MarkIDReply, error)
	SaveMatchToFile(context.Context, *SaveMatchToFileRequest) (*SaveMatchToFileReply, error)
	LoadMatchFromFile(context.Context, *LoadMatchFromFileRequest) (*LoadMatchFromFileReply, error)
}

// UnimplementedGOTV_PlusServer can be embedded to have forward compatible implementations.
type UnimplementedGOTV_PlusServer struct {
}

func (*UnimplementedGOTV_PlusServer) GetMatches(ctx context.Context, req *GetMatchesRequest) (*GetMatchesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (*UnimplementedGOTV_PlusServer) GetMatch(ctx context.Context, req *GetMatchRequest) (*Match, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatch not implemented")
}
func (*UnimplementedGOTV_PlusServer) DeleteMatch(ctx context.Context, req *DeleteMatchRequest) (*DeleteMatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMatch not implemented")
}
func (*UnimplementedGOTV_PlusServer) MarkID(ctx context.Context, req *MarkIDRequest) (*MarkIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkID not implemented")
}
func (*UnimplementedGOTV_PlusServer) SaveMatchToFile(ctx context.Context, req *SaveMatchToFileRequest) (*SaveMatchToFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMatchToFile not implemented")
}
func (*UnimplementedGOTV_PlusServer) LoadMatchFromFile(ctx context.Context, req *LoadMatchFromFileRequest) (*LoadMatchFromFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMatchFromFile not implemented")
}

func RegisterGOTV_PlusServer(s *grpc.Server, srv GOTV_PlusServer) {
	s.RegisterService(&_GOTV_Plus_serviceDesc, srv)
}

func _GOTV_Plus_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/GetMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_DeleteMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).DeleteMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/DeleteMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).DeleteMatch(ctx, req.(*DeleteMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_MarkID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).MarkID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/MarkID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).MarkID(ctx, req.(*MarkIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_SaveMatchToFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMatchToFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).SaveMatchToFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/SaveMatchToFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).SaveMatchToFile(ctx, req.(*SaveMatchToFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_LoadMatchFromFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMatchFromFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).LoadMatchFromFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/LoadMatchFromFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).LoadMatchFromFile(ctx, req.(*LoadMatchFromFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GOTV_Plus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GOTV_PLUS.GOTV_Plus",
	HandlerType: (*GOTV_PlusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatches",
			Handler:    _GOTV_Plus_GetMatches_Handler,
		},
		{
			MethodName: "GetMatch",
			Handler:    _GOTV_Plus_GetMatch_Handler,
		},
		{
			MethodName: "DeleteMatch",
			Handler:    _GOTV_Plus_DeleteMatch_Handler,
		},
		{
			MethodName: "MarkID",
			Handler:    _GOTV_Plus_MarkID_Handler,
		},
		{
			MethodName: "SaveMatchToFile",
			Handler:    _GOTV_Plus_SaveMatchToFile_Handler,
		},
		{
			MethodName: "LoadMatchFromFile",
			Handler:    _GOTV_Plus_LoadMatchFromFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gotv_plus.proto",
}
