// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gotv_plus.proto

package GOTV_PLUS

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Match struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{0}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Match) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetMatchesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesRequest) Reset()         { *m = GetMatchesRequest{} }
func (m *GetMatchesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchesRequest) ProtoMessage()    {}
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{1}
}

func (m *GetMatchesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesRequest.Unmarshal(m, b)
}
func (m *GetMatchesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesRequest.Merge(m, src)
}
func (m *GetMatchesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchesRequest.Size(m)
}
func (m *GetMatchesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesRequest proto.InternalMessageInfo

type GetMatchesReply struct {
	Match                []*Match `protobuf:"bytes,1,rep,name=match,proto3" json:"match,omitempty"`
	Error                bool     `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,3,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesReply) Reset()         { *m = GetMatchesReply{} }
func (m *GetMatchesReply) String() string { return proto.CompactTextString(m) }
func (*GetMatchesReply) ProtoMessage()    {}
func (*GetMatchesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{2}
}

func (m *GetMatchesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesReply.Unmarshal(m, b)
}
func (m *GetMatchesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesReply.Marshal(b, m, deterministic)
}
func (m *GetMatchesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesReply.Merge(m, src)
}
func (m *GetMatchesReply) XXX_Size() int {
	return xxx_messageInfo_GetMatchesReply.Size(m)
}
func (m *GetMatchesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesReply proto.InternalMessageInfo

func (m *GetMatchesReply) GetMatch() []*Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *GetMatchesReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *GetMatchesReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type GetMatchRequest struct {
	// Types that are valid to be assigned to Ids:
	//	*GetMatchRequest_Token
	//	*GetMatchRequest_Id
	Ids                  isGetMatchRequest_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMatchRequest) Reset()         { *m = GetMatchRequest{} }
func (m *GetMatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetMatchRequest) ProtoMessage()    {}
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{3}
}

func (m *GetMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchRequest.Unmarshal(m, b)
}
func (m *GetMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchRequest.Marshal(b, m, deterministic)
}
func (m *GetMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchRequest.Merge(m, src)
}
func (m *GetMatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetMatchRequest.Size(m)
}
func (m *GetMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchRequest proto.InternalMessageInfo

type isGetMatchRequest_Ids interface {
	isGetMatchRequest_Ids()
}

type GetMatchRequest_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type GetMatchRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*GetMatchRequest_Token) isGetMatchRequest_Ids() {}

func (*GetMatchRequest_Id) isGetMatchRequest_Ids() {}

func (m *GetMatchRequest) GetIds() isGetMatchRequest_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetMatchRequest) GetToken() string {
	if x, ok := m.GetIds().(*GetMatchRequest_Token); ok {
		return x.Token
	}
	return ""
}

func (m *GetMatchRequest) GetId() string {
	if x, ok := m.GetIds().(*GetMatchRequest_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetMatchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetMatchRequest_Token)(nil),
		(*GetMatchRequest_Id)(nil),
	}
}

type DeleteMatchRequest struct {
	// Types that are valid to be assigned to Ids:
	//	*DeleteMatchRequest_Token
	//	*DeleteMatchRequest_Id
	Ids                  isDeleteMatchRequest_Ids `protobuf_oneof:"ids"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeleteMatchRequest) Reset()         { *m = DeleteMatchRequest{} }
func (m *DeleteMatchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMatchRequest) ProtoMessage()    {}
func (*DeleteMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{4}
}

func (m *DeleteMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMatchRequest.Unmarshal(m, b)
}
func (m *DeleteMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMatchRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMatchRequest.Merge(m, src)
}
func (m *DeleteMatchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMatchRequest.Size(m)
}
func (m *DeleteMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMatchRequest proto.InternalMessageInfo

type isDeleteMatchRequest_Ids interface {
	isDeleteMatchRequest_Ids()
}

type DeleteMatchRequest_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type DeleteMatchRequest_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

func (*DeleteMatchRequest_Token) isDeleteMatchRequest_Ids() {}

func (*DeleteMatchRequest_Id) isDeleteMatchRequest_Ids() {}

func (m *DeleteMatchRequest) GetIds() isDeleteMatchRequest_Ids {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeleteMatchRequest) GetToken() string {
	if x, ok := m.GetIds().(*DeleteMatchRequest_Token); ok {
		return x.Token
	}
	return ""
}

func (m *DeleteMatchRequest) GetId() string {
	if x, ok := m.GetIds().(*DeleteMatchRequest_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteMatchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteMatchRequest_Token)(nil),
		(*DeleteMatchRequest_Id)(nil),
	}
}

type DeleteMatchReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMatchReply) Reset()         { *m = DeleteMatchReply{} }
func (m *DeleteMatchReply) String() string { return proto.CompactTextString(m) }
func (*DeleteMatchReply) ProtoMessage()    {}
func (*DeleteMatchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{5}
}

func (m *DeleteMatchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMatchReply.Unmarshal(m, b)
}
func (m *DeleteMatchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMatchReply.Marshal(b, m, deterministic)
}
func (m *DeleteMatchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMatchReply.Merge(m, src)
}
func (m *DeleteMatchReply) XXX_Size() int {
	return xxx_messageInfo_DeleteMatchReply.Size(m)
}
func (m *DeleteMatchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMatchReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMatchReply proto.InternalMessageInfo

func (m *DeleteMatchReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *DeleteMatchReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

type MarkIDRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDRequest) Reset()         { *m = MarkIDRequest{} }
func (m *MarkIDRequest) String() string { return proto.CompactTextString(m) }
func (*MarkIDRequest) ProtoMessage()    {}
func (*MarkIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{6}
}

func (m *MarkIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDRequest.Unmarshal(m, b)
}
func (m *MarkIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDRequest.Marshal(b, m, deterministic)
}
func (m *MarkIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDRequest.Merge(m, src)
}
func (m *MarkIDRequest) XXX_Size() int {
	return xxx_messageInfo_MarkIDRequest.Size(m)
}
func (m *MarkIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDRequest proto.InternalMessageInfo

func (m *MarkIDRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MarkIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MarkIDReply struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Errormessage         string   `protobuf:"bytes,2,opt,name=errormessage,proto3" json:"errormessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkIDReply) Reset()         { *m = MarkIDReply{} }
func (m *MarkIDReply) String() string { return proto.CompactTextString(m) }
func (*MarkIDReply) ProtoMessage()    {}
func (*MarkIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a69789a3c4d4fd, []int{7}
}

func (m *MarkIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkIDReply.Unmarshal(m, b)
}
func (m *MarkIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkIDReply.Marshal(b, m, deterministic)
}
func (m *MarkIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkIDReply.Merge(m, src)
}
func (m *MarkIDReply) XXX_Size() int {
	return xxx_messageInfo_MarkIDReply.Size(m)
}
func (m *MarkIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_MarkIDReply proto.InternalMessageInfo

func (m *MarkIDReply) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *MarkIDReply) GetErrormessage() string {
	if m != nil {
		return m.Errormessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Match)(nil), "GOTV_PLUS.Match")
	proto.RegisterType((*GetMatchesRequest)(nil), "GOTV_PLUS.GetMatchesRequest")
	proto.RegisterType((*GetMatchesReply)(nil), "GOTV_PLUS.GetMatchesReply")
	proto.RegisterType((*GetMatchRequest)(nil), "GOTV_PLUS.GetMatchRequest")
	proto.RegisterType((*DeleteMatchRequest)(nil), "GOTV_PLUS.DeleteMatchRequest")
	proto.RegisterType((*DeleteMatchReply)(nil), "GOTV_PLUS.DeleteMatchReply")
	proto.RegisterType((*MarkIDRequest)(nil), "GOTV_PLUS.MarkIDRequest")
	proto.RegisterType((*MarkIDReply)(nil), "GOTV_PLUS.MarkIDReply")
}

func init() { proto.RegisterFile("gotv_plus.proto", fileDescriptor_d8a69789a3c4d4fd) }

var fileDescriptor_d8a69789a3c4d4fd = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x4d, 0x52, 0x52, 0xda, 0xa9, 0xda, 0x3a, 0x4a, 0x09, 0x51, 0xa1, 0xec, 0x41, 0x7a, 0xb1,
	0x87, 0x8a, 0x17, 0xf1, 0x54, 0x2a, 0x89, 0xd8, 0xa2, 0xc4, 0x8f, 0x6b, 0x89, 0x66, 0xa9, 0xa1,
	0xa9, 0x89, 0xd9, 0x8d, 0xd0, 0xff, 0xe2, 0x8f, 0x95, 0x6c, 0x9a, 0x26, 0x21, 0xa9, 0x08, 0xbd,
	0xed, 0x7c, 0xbe, 0x79, 0xf3, 0x66, 0xa1, 0x3d, 0xf7, 0xf9, 0xf7, 0x2c, 0xf0, 0x22, 0x36, 0x08,
	0x42, 0x9f, 0xfb, 0xd8, 0x34, 0x1e, 0x9e, 0x5f, 0x67, 0x8f, 0x93, 0x97, 0x27, 0x72, 0x01, 0xea,
	0xd4, 0xe6, 0xef, 0x1f, 0x78, 0x0c, 0x2a, 0xf7, 0x17, 0xf4, 0x53, 0x93, 0x7b, 0x72, 0xbf, 0x69,
	0x25, 0x06, 0x1e, 0x80, 0xe2, 0x3a, 0x9a, 0x22, 0x5c, 0x8a, 0xeb, 0x90, 0x23, 0x38, 0x34, 0x28,
	0x17, 0x15, 0x94, 0x59, 0xf4, 0x2b, 0xa2, 0x8c, 0x13, 0x06, 0xed, 0xbc, 0x33, 0xf0, 0x56, 0x78,
	0x0e, 0xea, 0x32, 0xb6, 0x35, 0xb9, 0x57, 0xeb, 0xb7, 0x86, 0x9d, 0xc1, 0x06, 0x71, 0x20, 0xf2,
	0xac, 0x24, 0x1c, 0xa3, 0xd2, 0x30, 0xf4, 0x43, 0x01, 0xd1, 0xb0, 0x12, 0x03, 0x09, 0xec, 0x89,
	0xc7, 0x92, 0x32, 0x66, 0xcf, 0xa9, 0x56, 0x13, 0xf8, 0x05, 0x1f, 0x19, 0x65, 0xa0, 0xeb, 0x39,
	0xb0, 0x5b, 0xa0, 0x60, 0x4a, 0x29, 0x89, 0x4e, 0x46, 0xc2, 0x94, 0x62, 0x1a, 0x23, 0x15, 0x6a,
	0xae, 0xc3, 0xc8, 0x2d, 0xe0, 0x98, 0x7a, 0x94, 0xd3, 0xdd, 0xda, 0x4c, 0xa0, 0x53, 0x68, 0x13,
	0x2f, 0x60, 0x43, 0x4c, 0xfe, 0x8b, 0x98, 0x52, 0x41, 0xec, 0x0a, 0xf6, 0xa7, 0x76, 0xb8, 0xb8,
	0x1b, 0xa7, 0xf3, 0xfc, 0x4f, 0x19, 0x03, 0x5a, 0x69, 0xd9, 0x4e, 0xf8, 0xc3, 0x1f, 0x05, 0xd6,
	0xf7, 0xe1, 0x45, 0x0c, 0x4d, 0x80, 0x4c, 0x5b, 0x3c, 0xcd, 0xe9, 0x58, 0xba, 0x03, 0x5d, 0xdf,
	0x12, 0x0d, 0xbc, 0x15, 0x91, 0xf0, 0x1a, 0x1a, 0xa9, 0x13, 0xab, 0x32, 0xd3, 0x2e, 0xa5, 0x5b,
	0x21, 0x12, 0xde, 0x43, 0x2b, 0xb7, 0x61, 0x3c, 0xcb, 0xa5, 0x94, 0x05, 0xd4, 0x4f, 0xb6, 0x85,
	0x93, 0x41, 0x6e, 0xa0, 0x9e, 0x6c, 0x0a, 0xb5, 0x02, 0x54, 0x6e, 0xe7, 0x7a, 0xb7, 0x22, 0x22,
	0xaa, 0xdf, 0xea, 0xe2, 0x0b, 0x5d, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x44, 0x63, 0x78,
	0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GOTV_PlusClient is the client API for GOTV_Plus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GOTV_PlusClient interface {
	GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error)
	GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*Match, error)
	DeleteMatch(ctx context.Context, in *DeleteMatchRequest, opts ...grpc.CallOption) (*DeleteMatchReply, error)
	MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error)
}

type gOTV_PlusClient struct {
	cc *grpc.ClientConn
}

func NewGOTV_PlusClient(cc *grpc.ClientConn) GOTV_PlusClient {
	return &gOTV_PlusClient{cc}
}

func (c *gOTV_PlusClient) GetMatches(ctx context.Context, in *GetMatchesRequest, opts ...grpc.CallOption) (*GetMatchesReply, error) {
	out := new(GetMatchesReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) GetMatch(ctx context.Context, in *GetMatchRequest, opts ...grpc.CallOption) (*Match, error) {
	out := new(Match)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/GetMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) DeleteMatch(ctx context.Context, in *DeleteMatchRequest, opts ...grpc.CallOption) (*DeleteMatchReply, error) {
	out := new(DeleteMatchReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/DeleteMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gOTV_PlusClient) MarkID(ctx context.Context, in *MarkIDRequest, opts ...grpc.CallOption) (*MarkIDReply, error) {
	out := new(MarkIDReply)
	err := c.cc.Invoke(ctx, "/GOTV_PLUS.GOTV_Plus/MarkID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GOTV_PlusServer is the server API for GOTV_Plus service.
type GOTV_PlusServer interface {
	GetMatches(context.Context, *GetMatchesRequest) (*GetMatchesReply, error)
	GetMatch(context.Context, *GetMatchRequest) (*Match, error)
	DeleteMatch(context.Context, *DeleteMatchRequest) (*DeleteMatchReply, error)
	MarkID(context.Context, *MarkIDRequest) (*MarkIDReply, error)
}

// UnimplementedGOTV_PlusServer can be embedded to have forward compatible implementations.
type UnimplementedGOTV_PlusServer struct {
}

func (*UnimplementedGOTV_PlusServer) GetMatches(ctx context.Context, req *GetMatchesRequest) (*GetMatchesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (*UnimplementedGOTV_PlusServer) GetMatch(ctx context.Context, req *GetMatchRequest) (*Match, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatch not implemented")
}
func (*UnimplementedGOTV_PlusServer) DeleteMatch(ctx context.Context, req *DeleteMatchRequest) (*DeleteMatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMatch not implemented")
}
func (*UnimplementedGOTV_PlusServer) MarkID(ctx context.Context, req *MarkIDRequest) (*MarkIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkID not implemented")
}

func RegisterGOTV_PlusServer(s *grpc.Server, srv GOTV_PlusServer) {
	s.RegisterService(&_GOTV_Plus_serviceDesc, srv)
}

func _GOTV_Plus_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).GetMatches(ctx, req.(*GetMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_GetMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).GetMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/GetMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).GetMatch(ctx, req.(*GetMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_DeleteMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).DeleteMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/DeleteMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).DeleteMatch(ctx, req.(*DeleteMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GOTV_Plus_MarkID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GOTV_PlusServer).MarkID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GOTV_PLUS.GOTV_Plus/MarkID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GOTV_PlusServer).MarkID(ctx, req.(*MarkIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GOTV_Plus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GOTV_PLUS.GOTV_Plus",
	HandlerType: (*GOTV_PlusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatches",
			Handler:    _GOTV_Plus_GetMatches_Handler,
		},
		{
			MethodName: "GetMatch",
			Handler:    _GOTV_Plus_GetMatch_Handler,
		},
		{
			MethodName: "DeleteMatch",
			Handler:    _GOTV_Plus_DeleteMatch_Handler,
		},
		{
			MethodName: "MarkID",
			Handler:    _GOTV_Plus_MarkID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gotv_plus.proto",
}
