name: CI
on:
  push:
    branches: master
  pull_request:
    branches:
      - master

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build binary
      run: |
        make build-all
