name: CI
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Go test
      run: |
        go test -v -count=1 ./...
